### PR TITLE
this will sync my branch with your too i think

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by serejandmyself** [comment]
There are some conflicts. This means that there has been something changed that if merged, will cause some issues. In other words something went wrong somewhere along the way. Here, the only way to solve it is, for you, to manually see what can be causing those conflicts. The best way to do this is to take the previous version of the file:

https://github.com/citizen-cosmos/Awesome-cosmos-social

And try to carefully apply to pull request again

**Comment by ghost** [comment]
The changes are the additions i made today

**Comment by serejandmyself** [comment]
> The changes are the additions i made today

Yes, alas, one of them does conflict. Its manual work from here to find that conflict and resolve it, so the merge is possible

**Comment by ghost** [comment]
looks good man

**Pull request merged**
